"""Build the FX report: run the SQL in sql/, write results/REPORT.md and charts."""
import math
import sqlite3

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

from pipeline.config import DB_PATH, ROOT

SQL_DIR = ROOT / "sql"
OUT_DIR = ROOT / "results"
CHART_DIR = OUT_DIR / "charts"
USD_SPEND = 100_000  # illustrative monthly USD supplier spend

plt.rcParams.update({"axes.spines.top": False, "axes.spines.right": False,
                     "axes.grid": True, "grid.alpha": 0.3, "figure.dpi": 110})


def ensure_math(conn: sqlite3.Connection) -> None:
    """Register LN/SQRT if this SQLite build lacks the math extension (some CI runners)."""
    try:
        conn.execute("SELECT LN(1), SQRT(1)")
    except sqlite3.OperationalError:
        conn.create_function("LN", 1, math.log, deterministic=True)
        conn.create_function("SQRT", 1, math.sqrt, deterministic=True)


def query(conn, name: str, **params) -> pd.DataFrame:
    return pd.read_sql_query((SQL_DIR / name).read_text(), conn, params=params)


def chart_index(monthly: pd.DataFrame) -> None:
    wide = monthly.pivot(index="month", columns="quote", values="avg_rate")
    index = 100 * wide / wide.iloc[0]
    index.index = pd.to_datetime(index.index)
    last = index.iloc[-1].sort_values(ascending=False)
    fig, ax = plt.subplots(figsize=(10, 5.5))
    for quote in last.index:
        ax.plot(index.index, index[quote], lw=1.8, label=f"{quote} ({last[quote] - 100:+.1f}%)")
    ax.axhline(100, color="black", lw=0.8)
    ax.set_title("AUD strength vs each currency (monthly average, Jan 2023 = 100)")
    ax.set_ylabel("Index (above 100 = AUD buys more)")
    ax.legend(ncol=4, fontsize=9, loc="upper left", frameon=False)
    fig.tight_layout()
    fig.savefig(CHART_DIR / "01_aud_strength_index.png")
    plt.close(fig)


def chart_vol(vol: pd.DataFrame) -> None:
    vol = vol.sort_values("annual_vol_pct")
    fig, ax = plt.subplots(figsize=(8, 4.5))
    bars = ax.barh(vol["quote"], vol["annual_vol_pct"], color="#4C78A8")
    ax.bar_label(bars, fmt="%.1f%%", padding=3)
    ax.set_title("Annualised volatility of AUD pairs (daily log returns)")
    ax.set_xlabel("Volatility, % per year")
    fig.tight_layout()
    fig.savefig(CHART_DIR / "02_volatility.png")
    plt.close(fig)


def chart_budget(budget: pd.DataFrame) -> None:
    x = pd.to_datetime(budget["month"])
    colors = ["#54A24B" if v >= 0 else "#E45756" for v in budget["variance_aud"]]
    fig, ax = plt.subplots(figsize=(10, 4.5))
    ax.bar(x, budget["variance_aud"], width=20, color=colors)
    ax.axhline(0, color="black", lw=0.8)
    ax.set_title(f"Budget-rate variance on USD {USD_SPEND:,}/month of supplier invoices "
                 "(green = saved vs budget)")
    ax.set_ylabel("AUD vs budget")
    fig.tight_layout()
    fig.savefig(CHART_DIR / "03_budget_variance_usd.png")
    plt.close(fig)


def chart_policy(policy: pd.DataFrame) -> None:
    x = pd.to_datetime(policy["month"])
    fig, ax = plt.subplots(figsize=(10, 4.5))
    ax.bar(x - pd.Timedelta(days=5), policy["annual_error_aud"].abs(), width=10,
           color="#BAB0AC", label="Annual budget rate (previous December)")
    ax.bar(x + pd.Timedelta(days=5), policy["quarterly_error_aud"].abs(), width=10,
           color="#4C78A8", label="Quarterly re-forecast")
    ax.set_title(f"Monthly forecast miss on USD {USD_SPEND:,} of invoices: annual vs quarterly budget rate")
    ax.set_ylabel("Absolute error, AUD")
    ax.legend(frameon=False, loc="upper left")
    fig.tight_layout()
    fig.savefig(CHART_DIR / "04_budget_policy.png")
    plt.close(fig)


def main() -> None:
    CHART_DIR.mkdir(parents=True, exist_ok=True)
    with sqlite3.connect(DB_PATH) as conn:
        ensure_math(conn)
        strength = query(conn, "01_aud_strength.sql")
        vol = query(conn, "02_volatility.sql")
        budget = query(conn, "03_budget_variance.sql", usd_spend=USD_SPEND)
        monthly = query(conn, "04_monthly_index.sql")
        policy = query(conn, "05_budget_policy.sql", usd_spend=USD_SPEND)
        span = conn.execute("SELECT MIN(date), MAX(date), COUNT(*) FROM fx_rates").fetchone()

    chart_index(monthly)
    chart_vol(vol)
    chart_budget(budget)
    chart_policy(policy)

    budget["year"] = budget["month"].str[:4]
    by_year = (budget.groupby("year")
               .agg(months=("month", "count"), budget_rate=("budget_rate", "first"),
                    avg_actual=("actual_rate", "mean"), variance_aud=("variance_aud", "sum"))
               .round({"avg_actual": 4}).reset_index())

    policy["year"] = policy["month"].str[:4]
    errors = policy[["annual_error_aud", "quarterly_error_aud"]].abs()
    policy_year = (errors.groupby(policy["year"]).agg(["sum", "mean", "max"]).round(0))
    policy_year.columns = [f"{c}_abs_{agg}" for c, agg in policy_year.columns]
    policy_year = policy_year.reset_index()
    overall = errors.mean().round(0)

    md = [
        "# FX report (generated by `python -m report.build`)",
        "",
        f"Data: {span[2]:,} rows, {span[0]} to {span[1]}. Rates are units of quote currency per 1 AUD.",
        "",
        "## 1. AUD strength since the first date (`sql/01_aud_strength.sql`)",
        strength.to_markdown(index=False),
        "",
        "## 2. Volatility (`sql/02_volatility.sql`)",
        vol.to_markdown(index=False),
        "",
        f"## 3. Budget-rate variance, USD {USD_SPEND:,}/month (`sql/03_budget_variance.sql`)",
        "Budget rate = average AUD/USD of the previous December. Positive = cheaper than budget.",
        "",
        "### By year",
        by_year.to_markdown(index=False),
        "",
        "### By month",
        budget.drop(columns="year").to_markdown(index=False),
        "",
        "## 4. Annual vs quarterly budget rate (`sql/05_budget_policy.sql`)",
        "Quarterly = average AUD/USD of the month before each quarter starts. "
        "Errors are absolute AUD misses per month.",
        "",
        f"Mean monthly miss, all months: annual {overall['annual_error_aud']:,.0f} AUD, "
        f"quarterly {overall['quarterly_error_aud']:,.0f} AUD.",
        "",
        policy_year.to_markdown(index=False),
        "",
    ]
    (OUT_DIR / "REPORT.md").write_text("\n".join(md))
    print(f"wrote {OUT_DIR / 'REPORT.md'} and 4 charts")


if __name__ == "__main__":
    main()
